### PR TITLE
Configure logging using this gem

### PR DESCRIPTION
**Pull request by tijmenb**
GOV.UK applications use logstasher to output logs as JSON so they can be shipped to Kibana. 

Over the years copy-and-changing has led to a complete circus of different logging configurations. 

Here's a list of applications and versions:

Application  | Logstasher version
-- | --
asset-manager | 0.4.8
authenticating-proxy | 0.6.5
calculators | 0.6.5
calendars | 1.2.1
collections | 0.6.2
collections-publisher | 1.2.1
content-performance-manager | 1.2.1
content-store | 0.5.0
content-tagger | 1.2.1
design-principles | 0.4.8
email-alert-api | 1.2.1
feedback | 0.6.2
finder-frontend | 0.4.9
frontend | 1.1.0
government-frontend | 0.6.1
hmrc-manuals-api | 0.5.3
imminence | 0.4.8
info-frontend | 0.6.0
licence-finder | 0.6.5
link-checker-api | 0.9.0
local-links-manager | 0.6.2
manuals-frontend | 0.6.2
manuals-publisher | 0.4.8
maslow | 0.4.8
publisher | 1.2.1
publishing-api | 0.6.2
release | 0.4.8
router-api | 0.6.2
service-manual-frontend | 0.6.1
service-manual-publisher | 1.2.1
short-url-manager | 0.5.3
signon | 0.4.8
smart-answers | 0.4.8
specialist-publisher | 0.6.2
static | 0.4.8
support | 0.4.8
support-api | 0.6.2
transition | 0.6.5
travel-advice-publisher | 0.4.8
whitehall | 1.2.1

And the following apps don't use logstasher at all:

- bouncer
- contacts-admin
- email-alert-frontend
- policy-publisher
- search-admin

This PR adds logstasher as a dependency and sets up an initialiser to set it up correctly. By centralising the config we can get rid of divergent config in different apps and use the same version everywhere.

We're doing this now because we need to [bump the logstasher gem in all apps to make it work with log.it](https://github.com/alphagov/govuk-puppet/pull/6650). Moving the config into this gem now will make future upgrade processes easier.

## Todo

- [x] ~Add tests~ it's crazy hard to test this..
- [x] Add documentation
- [x] Fix logstasher crashing: https://github.com/shadabahmed/logstasher/pull/142
- [x] Test with Rails app & non-Rails apps (bouncer, rummager, email-alert-service)

### CODE REVIEW

**Comment by jennyd** [comment]
On bouncer not using logstasher: we didn't make bouncer log requests from the application in the past because we thought it wouldn't add much to what the nginx logs already give us. Upstart logs cover the app being unable to start, and other exceptions should be logged to Sentry. That isn't necessarily still a good reason to not do it, if consistency is more important to us now.

**Comment by tijmenb** [comment]
Tested this on https://github.com/alphagov/collections/pull/392.

Blue is STDERR, white STDOUT:

screen shot 2017-11-08 at 12 43 10

√ Logs JSON to SDTOUT
√ Logs `Rails.logger.info` to STDERR
√ Logs other cruft to STDERR

**Comment by chrisroos** [comment]
Hey @tijmenb. Can this be reviewed, or should it wait until you've ticked off the final item in the todo list ("Test with Rails app & non-Rails apps (bouncer, rummager, email-alert-service)")?

**Comment by tijmenb** [comment]
@chrisroos yes! That would be great. I've only been meaning to test it on integration.

**Comment by tijmenb** [comment]
I've tried this on integration (via https://github.com/alphagov/collections/pull/392) and it works, data is being sent correctly.

screen shot 2017-11-28 at 18 53 36

https://kibana.logit.io/app/kibana#/doc/*/filebeat-2017.11.28/log?id=AWAD-GgN14uVNDqnd4Nk&_g=()

@kevindew would you like to review?

**Comment by chrisroos** [comment]
Apologies for not making the time to review this, @tijmenb. Good work on getting it merged :-)

**Pull request merged**
